### ISSUE TITLE
Tool crash due to faulty parsing of artifact version

### ISSUE THREAD

**Issue by mkrutov** [release-engineering/offliner#48] opened 2019-09-10 16:13 UTC
`java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Illegal character in path at index 77: https://maven.repository.redhat.com/ga/all/org/owasp/dependency-check-maven/${owasp.version}/dependency-check-maven-${owasp.version}.pom
`

full log:
**REDACTED**

pom.xml in question: https://github.com/rh-messaging/activemq-artemis/blob/2.9.0.jbossorg-x/pom.xml

**Comment by jdcasey** [comment] 2019-09-10 16:52
Is this using a pom.xml as input or something?

**Comment by jdcasey** [comment] 2019-09-11 12:38
Looking at the logs, this is a duplicate of #4

**Closed by jdcasey** 2019-09-11 12:38 UTC
